version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8080:80'
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
